# Generated by Django 5.2.5 on 2025-09-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('country', models.TextField(verbose_name='Страна происхождения')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название турнира')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('TBA', 'TBA'), ('Coming', 'Coming'), ('Live', 'Live'), ('Ended', 'Ended')], default='TBA', max_length=6)),
                ('prize_pool', models.IntegerField(verbose_name='Призовой фонд')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(verbose_name='Псевдоним')),
                ('real_name', models.TextField(verbose_name='Настоящее имя')),
                ('role', models.TextField(verbose_name='Роль')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dotaesports.team')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('status', models.CharField(choices=[('TBA', 'TBA'), ('Coming', 'Coming'), ('Live', 'Live'), ('Ended', 'Ended')], default='TBA', max_length=6)),
                ('dire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dire_matches', to='dotaesports.team')),
                ('radiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiant_matches', to='dotaesports.team')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dotaesports.tournament')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='TournamentTeamParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dotaesports.team')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dotaesports.tournament')),
            ],
            options={
                'verbose_name': 'Участие команды',
                'verbose_name_plural': 'Участия команды',
            },
        ),
    ]
