# Generated by Django 5.2.5 on 2025-09-04 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='dire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dire_matches', to='dotaesports.team', verbose_name='Силы Тьмы'),
        ),
        migrations.AlterField(
            model_name='match',
            name='radiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiant_matches', to='dotaesports.team', verbose_name='Силы Света'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('TBA', 'Неизвестно'), ('Coming', 'Скоро начнётся'), ('Live', 'Идёт'), ('Ended', 'Закончен')], default='TBA', max_length=6),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dotaesports.tournament', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dotaesports.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('TBA', 'Неизвестно'), ('Coming', 'Скоро начнётся'), ('Live', 'Идёт'), ('Ended', 'Закончен')], default='TBA', max_length=6),
        ),
        migrations.AlterField(
            model_name='tournamentteamparticipation',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dotaesports.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='tournamentteamparticipation',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dotaesports.tournament', verbose_name='Турнир'),
        ),
    ]
