# Generated by Django 5.2.5 on 2025-09-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0002_alter_match_dire_alter_match_radiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('TBA', 'Неизвестно'), ('Coming', 'Скоро начнётся'), ('Live', 'Идёт'), ('Ended', 'Закончен')], default='TBA', max_length=6, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dotaesports.tournament', verbose_name='Турнир'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('TBA', 'Неизвестно'), ('CARRY', 'Керри'), ('MIDLANER', 'Мидлейнер'), ('HARDLINER', 'Тройка'), ('SEMISUPPORT', 'Четвёрка'), ('FULLSUPPORT', 'Пятёрка')], default='TBA', max_length=11, verbose_name='Роль'),
        ),
    ]
