# Generated by Django 5.2.5 on 2025-09-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0003_alter_match_status_alter_match_tournament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(choices=[('TBA', 'Неизвестно'), ('RADIANT', 'Силы Света'), ('DIRE', 'Силы Тьмы')], default='TBA', max_length=7, verbose_name='Победитель'),
        ),
    ]
