# Generated by Django 5.2.5 on 2025-09-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0004_remove_match_status_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteamparticipation',
            name='place',
            field=models.IntegerField(default=0, verbose_name='Место'),
        ),
    ]
