# Generated by Django 5.2.5 on 2025-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0005_tournamentteamparticipation_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='prize_pool',
            field=models.IntegerField(verbose_name='Призовой фонд (в рублях)'),
        ),
        migrations.AlterField(
            model_name='tournamentteamparticipation',
            name='place',
            field=models.IntegerField(default='0', verbose_name='Место'),
        ),
    ]
