# Generated by Django 5.2.5 on 2025-09-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0006_alter_tournament_prize_pool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentteamparticipation',
            name='place',
            field=models.IntegerField(verbose_name='Место'),
        ),
    ]
