# Generated by Django 5.2.5 on 2025-09-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0007_alter_tournamentteamparticipation_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentteamparticipation',
            name='place',
        ),
    ]
