# Generated by Django 5.2.5 on 2025-09-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0008_remove_tournamentteamparticipation_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteamparticipation',
            name='place',
            field=models.IntegerField(default=0, verbose_name='Место'),
        ),
    ]
