# Generated by Django 5.2.5 on 2025-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0012_alter_tournamentteamparticipation_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('CARRY', 'Керри'), ('MIDLANER', 'Мидлейнер'), ('HARDLINER', 'Тройка'), ('SEMISUPPORT', 'Четвёрка'), ('FULLSUPPORT', 'Пятёрка')], max_length=11, verbose_name='Роль'),
        ),
    ]
