# Generated by Django 5.2.5 on 2025-10-15 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0015_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='dotaesports.team', verbose_name='Победитель'),
        ),
    ]
