# Generated by Django 5.2.5 on 2025-10-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0017_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.TextField(null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='player',
            name='real_name',
            field=models.TextField(null=True, verbose_name='Настоящее имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('CARRY', 'Керри'), ('MIDLANER', 'Мидлейнер'), ('HARDLINER', 'Тройка'), ('SEMISUPPORT', 'Четвёрка'), ('FULLSUPPORT', 'Пятёрка')], max_length=11, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.TextField(null=True, verbose_name='Страна происхождения'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.TextField(null=True, verbose_name='Название турнира'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_pool',
            field=models.IntegerField(null=True, verbose_name='Призовой фонд (в рублях)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('TBA', 'Неизвестно'), ('Coming', 'Скоро начнётся'), ('Live', 'Идёт'), ('Ended', 'Закончен')], default='TBA', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentteamparticipation',
            name='place',
            field=models.IntegerField(default=0, null=True, verbose_name='Место'),
        ),
    ]
