# Generated by Django 5.2.5 on 2025-11-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0020_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(null=True, upload_to='players', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(null=True, upload_to='teams', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(null=True, upload_to='tournaments', verbose_name='Изображение'),
        ),
    ]
