# Generated by Django 5.2.5 on 2025-11-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0023_remove_player_user_player_by_user_team_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='by_user',
            new_name='user',
        ),
    ]
