# Generated by Django 5.2.5 on 2025-12-02 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0024_rename_by_user_player_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentteamparticipation',
            options={'ordering': ['place'], 'verbose_name': 'Участие команды', 'verbose_name_plural': 'Участия команды'},
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='dotaesports.team', verbose_name='Победитель'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentteamparticipation',
            unique_together={('tournament', 'team')},
        ),
        migrations.CreateModel(
            name='PlayerTeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_team_history', to=settings.AUTH_USER_MODEL, verbose_name='Кто переводил')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dotaesports.team', verbose_name='Команда')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кого переводили')),
            ],
            options={
                'verbose_name': 'История команд игрока',
                'verbose_name_plural': 'Истории команд игроков',
                'ordering': ['-created_at'],
            },
        ),
    ]
