# Generated by Django 5.2.5 on 2025-12-02 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0025_alter_tournamentteamparticipation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerteamhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='playerteamhistory',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_history', to='dotaesports.player', verbose_name='Кого переводили'),
        ),
    ]
