# Generated by Django 5.2.5 on 2025-12-17 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaesports', '0028_remove_player_player_profile_player_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='by_user',
        ),
        migrations.AlterField(
            model_name='match',
            name='dire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dire_matches', to='dotaesports.team', verbose_name='Силы Тьмы'),
        ),
        migrations.AlterField(
            model_name='match',
            name='radiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiant_matches', to='dotaesports.team', verbose_name='Силы Света'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dotaesports.tournament', verbose_name='Турнир'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dotaesports.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='playerteamhistory',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_team_history', to=settings.AUTH_USER_MODEL, verbose_name='Кто переводил'),
        ),
        migrations.AlterField(
            model_name='playerteamhistory',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_history', to='dotaesports.player', verbose_name='Кого переводили'),
        ),
        migrations.AlterField(
            model_name='playerteamhistory',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dotaesports.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='tournamentteamparticipation',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dotaesports.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='tournamentteamparticipation',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dotaesports.tournament', verbose_name='Турнир'),
        ),
    ]
